'use client';

import React, { useRef, useEffect, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useLenis } from '../hooks/useLenis';
import { useImagePreloader } from '../hooks/useImagePreloader';
import { useSequenceRenderer } from '../hooks/useSequenceRenderer';
import { SequenceCanvas } from './SequenceCanvas';
import { HUDOverlay } from './HUDOverlay';

// Register ScrollTrigger client-side
if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

const TOTAL_FRAMES = 179; // 179 frames generated by 30 FPS video
const SCROLL_LENGTH = '+=400%'; // Standard scroll height
const getFrameUrl = (idx: number) => `/frames/frame_${String(idx).padStart(5, '0')}.webp`;

export function HeroSequence() {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // States to drive real-time telemetry and HUD animations
  const [scrollProgress, setScrollProgress] = useState(0);
  const [activeSection, setActiveSection] = useState(0);

  // Debugging states for looping loader and entering site
  const [loopProgress, setLoopProgress] = useState(0);
  const [dotCycle, setDotCycle] = useState(0);
  const [showLoader, setShowLoader] = useState(true);
  const [isFadingOut, setIsFadingOut] = useState(false);

  // 1. Initialize Lenis smooth scroll and connect to GSAP
  useLenis();

  // 2. Preload & pre-decode the 179 WebP frames
  const { frames, progress, isLoaded, error } = useImagePreloader(TOTAL_FRAMES, getFrameUrl);

  // Smooth transition from loading screen to main site
  useEffect(() => {
    if (isLoaded) {
      const fadeTimer = setTimeout(() => {
        setIsFadingOut(true);
        const removeTimer = setTimeout(() => {
          setShowLoader(false);
        }, 800);
        return () => clearTimeout(removeTimer);
      }, 500);
      return () => clearTimeout(fadeTimer);
    }
  }, [isLoaded]);

  // Auto-loop progress and dot loader cycle timers
  useEffect(() => {
    const progressInterval = setInterval(() => {
      setLoopProgress((prev) => (prev >= 100 ? 0 : prev + 2));
    }, 50);

    const dotInterval = setInterval(() => {
      setDotCycle((prev) => (prev + 1) % 3);
    }, 350);

    return () => {
      clearInterval(progressInterval);
      clearInterval(dotInterval);
    };
  }, []);

  // 3. Connect Canvas renderer to ScrollTrigger and the GSAP ticker
  useSequenceRenderer({
    canvasRef,
    containerRef,
    frames,
    isLoaded,
    totalFrames: TOTAL_FRAMES,
    smoothingFactor: 0.4, // Faster responsive tracking during active scroll
    scrollLength: SCROLL_LENGTH,
  });

  // 4. Synchronize scroll progress state with ScrollTrigger in real-time
  useEffect(() => {
    if (!isLoaded || !containerRef.current) return;

    const scrollTriggerInstance = ScrollTrigger.create({
      trigger: containerRef.current,
      start: 'top top',
      end: SCROLL_LENGTH,
      scrub: true,
      onUpdate: (self) => {
        setScrollProgress(self.progress);
        // Map scroll progress to 5 discrete sections (0 to 4)
        const section = Math.min(4, Math.floor(self.progress * 5));
        setActiveSection(section);
      },
    });

    return () => {
      scrollTriggerInstance.kill();
    };
  }, [isLoaded]);

  const loadingStages = [
    'CONNECTING NEURAL SYNC...',
    'PARSING DISASSEMBLY VECTORS...',
    'LOADING GRADE-5 TITANIUM MESH...',
    'INITIALIZING WEBGL SHADER BUFFERS...',
    'NOMINAL STATE COMPILED // READY',
  ];
  // Map current loop progress (0-100) to stages
  const currentStage = loadingStages[Math.min(loadingStages.length - 1, Math.floor((loopProgress / 100) * loadingStages.length))];

  // Helper to compute dot animation classes (1st=green, 2nd=white, 3rd=gray rotating)
  const getDotClass = (dotIndex: number) => {
    const relativePos = (dotIndex - dotCycle + 3) % 3;
    if (relativePos === 0) {
      // Theme green
      return 'bg-accent shadow-[0_0_10px_rgba(163,230,53,0.95)] opacity-100 scale-110';
    } else if (relativePos === 1) {
      // Lite white
      return 'bg-white/90 opacity-90';
    } else {
      // Gray
      return 'bg-zinc-600/60 opacity-50';
    }
  };

  return (
    <div ref={containerRef} className="relative w-full bg-black select-none">
      {/* Pinned Viewport Container holding the canvas */}
      <div className="sticky top-0 left-0 w-full h-screen overflow-hidden flex items-center justify-center bg-black">
        {/* Immersive background canvas */}
        <div className="absolute inset-0 w-full h-full">
          <SequenceCanvas ref={canvasRef} />
        </div>

        {/* Ambient shadow gradient overlays for optimal text legibility */}
        <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-transparent to-black/60 pointer-events-none" />

        {/* Premium Sci-Fi HUD Overlay */}
        <HUDOverlay startEntry={isFadingOut} scrollProgress={scrollProgress} activeSection={activeSection} />
      </div>

      {/* High-fidelity HUD preloader overlay */}
      {showLoader && (
        <div 
          className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black text-white font-mono select-none overflow-hidden"
          style={{
            transition: 'opacity 0.8s cubic-bezier(0.16, 1, 0.3, 1), transform 0.8s cubic-bezier(0.16, 1, 0.3, 1)',
            opacity: isFadingOut ? 0 : 1,
            transform: isFadingOut ? 'scale(0.96) translateY(-10px)' : 'scale(1) translateY(0)',
            pointerEvents: isFadingOut ? 'none' : 'auto'
          }}
        >
          {/* Ambient background accent light */}
          <div className="absolute w-[500px] h-[500px] rounded-full bg-accent/5 blur-3xl pointer-events-none" />

          {/* Outer Grid Crosses Container */}
          <div className="relative flex flex-col items-center w-full max-w-[540px] px-6">
            
            {/* Top Center Box */}
            <div className="absolute -top-[16px] left-1/2 -translate-x-1/2 flex flex-col items-center">
              <span className="text-[6px] text-accent/75 tracking-[0.2em] font-bold mb-1 select-none animate-pulse">
                ///////////////
              </span>
              <div className="w-20 h-2 bg-zinc-950 border border-white/10 border-b-0" />
            </div>

            {/* Main Central Card Block */}
            <div className="w-full bg-zinc-950/80 border border-white/10 px-6 py-6 flex flex-col justify-between select-none relative z-10">
              
              {/* Left Bracket - enclosing the main card block */}
              <div className="absolute -left-6 md:-left-8 -top-2 -bottom-2 w-3 border-t border-b border-l border-white/25 flex items-center justify-start pointer-events-none">
                <div className="w-1.5 h-[1px] bg-white/25" />
              </div>

              {/* Right Bracket - enclosing the main card block */}
              <div className="absolute -right-6 md:-right-8 -top-2 -bottom-2 w-3 border-t border-b border-r border-white/25 flex items-center justify-end pointer-events-none">
                <div className="w-1.5 h-[1px] bg-white/25" />
              </div>

              {/* Top Section: Diagnostics telemetry paragraphs */}
              <div className="flex justify-between items-start w-full">
                {/* Left Paragraph: Text and Icon */}
                <div className="flex gap-3 items-center">
                  {/* SVG Screen/Monitor Icon with '+' */}
                  <div className="w-9 h-9 flex items-center justify-center bg-zinc-900/50 border border-white/5 flex-shrink-0">
                    <svg className="w-5 h-5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5">
                      <rect x="2" y="4" width="20" height="12" rx="1" />
                      <path d="M8 20h8M12 16v4" />
                      <path d="M12 8v4M10 10h4" stroke="#a3e635" strokeWidth="2" />
                    </svg>
                  </div>
                  {/* Subtext info */}
                  <div className="flex flex-col text-[7px] text-zinc-500 leading-normal tracking-wider uppercase">
                    <span>PRELOADER SEQUENCE // OS</span>
                    <span>SYNEX Grade-5 titanium shell</span>
                    <span>neural interface loading</span>
                  </div>
                </div>
                
                {/* Right Paragraph: Status and Rev */}
                <div className="flex flex-col items-end text-[7px] text-zinc-500 leading-normal tracking-wider uppercase text-right">
                  <span className="text-accent">SYS_REV_2.4</span>
                  <span>BOOT_FLOW // OK</span>
                  <span>CAL_INDEX: {loopProgress}%</span>
                </div>
              </div>

              {/* Middle Section: Word SYNEX and Diamonds */}
              <div className="flex justify-between items-center my-6">
                {/* Main Title */}
                <h1 className="text-3xl md:text-4xl font-sans font-black tracking-[0.2em] text-white uppercase leading-none">
                  SYNEX
                </h1>
                
                {/* Diamond and loading stripe cluster */}
                <div className="flex items-center gap-4">
                  {/* Custom Danger/Loading stripes */}
                  <div className="w-6 h-2 bg-[repeating-linear-gradient(45deg,rgba(163,230,53,0.6)_0px,rgba(163,230,53,0.6)_2px,transparent_2px,transparent_4px)]" />

                  {/* Triple Dot Loader */}
                  <div className="flex items-center gap-2 h-6 flex-shrink-0">
                    {/* 1st dot (theme green in state 0) */}
                    <div className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${getDotClass(0)}`} />
                    {/* 2nd dot (lite white in state 0) */}
                    <div className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${getDotClass(1)}`} />
                    {/* 3rd dot (gray in state 0) */}
                    <div className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${getDotClass(2)}`} />
                  </div>
                </div>
              </div>

              {/* Solid Divider Line acting as a loading progress bar */}
              <div className="w-full h-[2px] bg-white/10 mb-3 relative overflow-hidden">
                <div 
                  className="h-full bg-white transition-all duration-150 ease-out"
                  style={{ width: `${loopProgress}%` }}
                />
              </div>

              {/* Lower Section: Project context details */}
              <div className="flex flex-col text-left">
                {/* Context text (changing stage + progress info) */}
                <div className="text-[10px] md:text-[11px] font-mono tracking-[0.15em] text-zinc-200 uppercase">
                  {loopProgress}% EXOSKELETON DISASSEMBLY LOADED
                </div>
                <div className="text-[8px] font-mono tracking-[0.1em] text-zinc-500 uppercase mt-1">
                  STAGE // {currentStage}
                </div>
              </div>
            </div>

            {error && (
              <p className="mt-8 text-[9px] text-red-400 tracking-widest font-mono bg-red-950/20 border border-red-500/10 px-4 py-2 rounded-none">
                WARNING // {error}
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export default HeroSequence;
