'use client';

import React, { useRef, useEffect } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useLenis } from '../hooks/useLenis';
import { useImagePreloader } from '../hooks/useImagePreloader';
import { useSequenceRenderer } from '../hooks/useSequenceRenderer';
import { SequenceCanvas } from './SequenceCanvas';

// Register ScrollTrigger client-side
if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

const TOTAL_FRAMES = 179; // 179 frames generated by 30 FPS video
const SCROLL_LENGTH = '+=400%'; // Standard scroll height
const getFrameUrl = (idx: number) => `/frames/frame_${String(idx).padStart(5, '0')}.webp`;

export function HeroSequence() {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // Overlay text refs for ScrollTrigger synchronization
  const introRef = useRef<HTMLDivElement>(null);
  const layer1Ref = useRef<HTMLDivElement>(null);
  const layer2Ref = useRef<HTMLDivElement>(null);
  const layer3Ref = useRef<HTMLDivElement>(null);
  const outroRef = useRef<HTMLDivElement>(null);

  // 1. Initialize Lenis smooth scroll and connect to GSAP
  useLenis();

  // 2. Preload & pre-decode the 89 WebP frames
  const { frames, progress, isLoaded, error } = useImagePreloader(TOTAL_FRAMES, getFrameUrl);

  // 3. Connect Canvas renderer to ScrollTrigger and the GSAP ticker
  useSequenceRenderer({
    canvasRef,
    containerRef,
    frames,
    isLoaded,
    totalFrames: TOTAL_FRAMES,
    smoothingFactor: 0.4, // Faster responsive tracking during active scroll
    scrollLength: SCROLL_LENGTH,
  });

  // 4. Orchestrate overlapping text animations in sync with scroll progress
  useEffect(() => {
    if (!isLoaded || !containerRef.current) return;

    const ctx = gsap.context(() => {
      // Create a master timeline locked to the container's pinning scroll with smooth catch-up
      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: containerRef.current,
          start: 'top top',
          end: SCROLL_LENGTH,
          scrub: true, // Matches the canvas sequence perfectly without added lag
        },
      });

      // Default hidden states set by CSS but managed here
      gsap.set([introRef.current, layer1Ref.current, layer2Ref.current, layer3Ref.current, outroRef.current], {
        opacity: 0,
        y: 60,
      });

      // TIMELINE ORCHESTRATION (Relative offsets sync text triggers with mask disassembly frames)
      
      // Step 1: Intro Text (Title fades in immediately, stays, and fades out)
      tl.to(introRef.current, { opacity: 1, y: 0, duration: 1.5 })
        .to(introRef.current, { opacity: 0, y: -60, duration: 1.5 }, '+=1.0')

      // Step 2: Feature Layer 1: Titanium Exoskeleton
        .to(layer1Ref.current, { opacity: 1, y: 0, duration: 1.5 }, '+=0.5')
        .to(layer1Ref.current, { opacity: 0, y: -60, duration: 1.5 }, '+=1.2')

      // Step 3: Feature Layer 2: Optic Sensors
        .to(layer2Ref.current, { opacity: 1, y: 0, duration: 1.5 }, '+=0.5')
        .to(layer2Ref.current, { opacity: 0, y: -60, duration: 1.5 }, '+=1.2')

      // Step 4: Feature Layer 3: Neural Link Nodes
        .to(layer3Ref.current, { opacity: 1, y: 0, duration: 1.5 }, '+=0.5')
        .to(layer3Ref.current, { opacity: 0, y: -60, duration: 1.5 }, '+=1.2')

      // Step 5: Cinematic Outro (Disassembly complete)
        .to(outroRef.current, { opacity: 1, y: 0, duration: 1.5 }, '+=0.5')
        .to(outroRef.current, { opacity: 0, duration: 1.5 }, '+=1.5');
    }, containerRef);

    return () => ctx.revert(); // Clean up GSAP timelines on unmount
  }, [isLoaded]);

  // Premium, immersive Apple-style loading screen
  if (!isLoaded) {
    return (
      <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black text-white font-sans">
        <div className="relative flex flex-col items-center max-w-md w-full px-8">
          {/* Subtle glowing ring background */}
          <div className="absolute -top-12 w-36 h-36 rounded-full bg-indigo-500/10 blur-2xl animate-pulse" />
          
          <h2 className="text-xs uppercase tracking-[0.3em] text-zinc-400 font-semibold mb-6 text-center">
            Initializing neural interface
          </h2>

          {/* Loader bar container */}
          <div className="w-full h-[2px] bg-zinc-800 rounded-full overflow-hidden mb-4 relative">
            <div 
              className="h-full bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500 transition-all duration-300 ease-out shadow-[0_0_10px_rgba(99,102,241,0.5)]"
              style={{ width: `${progress}%` }}
            />
          </div>

          {/* Load values */}
          <div className="flex w-full justify-between text-[11px] font-mono tracking-widest text-zinc-500 uppercase">
            <span>Progress</span>
            <span className="text-zinc-300 font-bold">{progress}%</span>
          </div>

          {error && (
            <p className="mt-6 text-xs text-red-400 tracking-wider font-mono bg-red-950/20 border border-red-500/10 px-4 py-2 rounded-md">
              ⚠️ {error}
            </p>
          )}
        </div>
      </div>
    );
  }

  return (
    <div ref={containerRef} className="relative w-full bg-black select-none">
      {/* Pinned Viewport Container holding the canvas */}
      <div className="sticky top-0 left-0 w-full h-screen overflow-hidden flex items-center justify-center bg-black">
        {/* Immersive background canvas */}
        <div className="absolute inset-0 w-full h-full">
          <SequenceCanvas ref={canvasRef} />
        </div>

        {/* Ambient shadow gradient overlays for optimal text legibility */}
        <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/80 pointer-events-none" />

        {/* Synchronized HUD-like text layers */}
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <div className="w-full max-w-6xl px-8 md:px-16 relative h-full flex flex-col justify-center">
            
            {/* Overlay 1: Cinematic Intro Title */}
            <div ref={introRef} className="absolute self-center text-center w-full max-w-xl px-6">
              <h1 className="text-4xl md:text-7xl font-bold tracking-[-0.03em] leading-tight text-white mb-6 uppercase">
                CYBERNETIC <br/>
                <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 via-indigo-300 to-purple-400">
                  EXOSKELETON
                </span>
              </h1>
              <p className="text-sm md:text-base tracking-[0.25em] uppercase text-zinc-400 font-medium font-sans">
                Scroll to disassemble
              </p>
            </div>

            {/* Overlay 2: Feature Layer 1 */}
            <div ref={layer1Ref} className="absolute bottom-16 left-6 right-6 w-auto max-w-sm mx-auto text-center px-6 py-4 bg-black/60 backdrop-blur-sm border border-white/5 rounded-xl md:left-16 md:right-auto md:bottom-auto md:w-full md:max-w-md md:text-left md:px-0 md:py-0 md:bg-transparent md:backdrop-blur-none md:border-none md:rounded-none">
              <span className="text-[10px] md:text-xs font-mono font-bold tracking-widest text-indigo-400 uppercase mb-2 block">
                [ 01 / STRUCTURAL LAYER ]
              </span>
              <h3 className="text-2xl md:text-5xl font-semibold text-white tracking-tight leading-none mb-4 uppercase">
                Titanium Alloy Shell
              </h3>
              <p className="text-xs md:text-base text-zinc-400 leading-relaxed font-light">
                Grade-5 forged metallic exoskeleton provides unmatched structural shielding and micro-impact absorption. Engineered for maximum weight-to-strength efficiency.
              </p>
            </div>

            {/* Overlay 3: Feature Layer 2 */}
            <div ref={layer2Ref} className="absolute bottom-16 left-6 right-6 w-auto max-w-sm mx-auto text-center px-6 py-4 bg-black/60 backdrop-blur-sm border border-white/5 rounded-xl md:left-auto md:right-16 md:bottom-auto md:w-full md:max-w-md md:text-left md:px-0 md:py-0 md:bg-transparent md:backdrop-blur-none md:border-none md:rounded-none">
              <span className="text-[10px] md:text-xs font-mono font-bold tracking-widest text-blue-400 uppercase mb-2 block">
                [ 02 / SENSORY MATRIX ]
              </span>
              <h3 className="text-2xl md:text-5xl font-semibold text-white tracking-tight leading-none mb-4 uppercase">
                Micro-OLED Cortex
              </h3>
              <p className="text-xs md:text-base text-zinc-400 leading-relaxed font-light">
                Dual 8K micro-OLED ocular arrays deliver real-time environmental diagnostics, neural-feed projections, and seamless overlay of telemetry directly into your optic nerve.
              </p>
            </div>

            {/* Overlay 4: Feature Layer 3 */}
            <div ref={layer3Ref} className="absolute bottom-16 left-6 right-6 w-auto max-w-sm mx-auto text-center px-6 py-4 bg-black/60 backdrop-blur-sm border border-white/5 rounded-xl md:left-16 md:right-auto md:bottom-auto md:w-full md:max-w-md md:text-left md:px-0 md:py-0 md:bg-transparent md:backdrop-blur-none md:border-none md:rounded-none">
              <span className="text-[10px] md:text-xs font-mono font-bold tracking-widest text-purple-400 uppercase mb-2 block">
                [ 03 / BIO-LINK SYSTEM ]
              </span>
              <h3 className="text-2xl md:text-5xl font-semibold text-white tracking-tight leading-none mb-4 uppercase">
                Synaptic Interface
              </h3>
              <p className="text-xs md:text-base text-zinc-400 leading-relaxed font-light">
                Integrated neuro-link receivers directly interface with the cerebral cortex, translating motor commands into low-latency cybernetic telemetry.
              </p>
            </div>

            {/* Overlay 5: Outro Layer */}
            <div ref={outroRef} className="absolute self-center text-center w-full max-w-2xl px-6">
              <h2 className="text-4xl md:text-7xl font-extrabold tracking-[-0.03em] leading-tight text-white mb-6 uppercase">
                SYSTEM FULLY <br />
                <span className="bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-400">
                  DISASSEMBLED
                </span>
              </h2>
              <p className="text-sm md:text-base tracking-[0.2em] uppercase text-zinc-400 font-medium">
                Prototype v1.0. All components responsive.
              </p>
            </div>

          </div>
        </div>

        {/* HUD Indicator in Corner */}
        <div className="absolute top-6 left-6 md:top-auto md:bottom-6 md:left-16 pointer-events-none flex items-center gap-4 text-zinc-500 font-mono text-[10px] tracking-[0.2em] uppercase">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
          <span>SYNEX // DISASSEMBLY MODE</span>
        </div>
      </div>
    </div>
  );
}

export default HeroSequence;
